# docker build -t ws4sqlite .

FROM golang:latest as build

RUN apt-get update
RUN apt-get full-upgrade -y

WORKDIR /go/src/app
COPY . .

RUN make build

# Now copy it into our base image.
FROM gcr.io/distroless/static-debian11
COPY --from=build /go/src/app/bin/ws4sqlite /

ENTRYPOINT ["/ws4sqlite"]